USE DATABASE INGEST_DB;

CREATE OR REPLACE STORAGE INTEGRATION s3_ingest_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/<SNOWFLAKE_S3_ROLE_NAME>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<YOUR_BUCKET_NAME>/<YOUR_PREFIX>/');

-- Example:
-- STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::123456789012:role/snowflake_s3_ingest_role'
-- STORAGE_ALLOWED_LOCATIONS = ('s3://rnz-snowflake-export-text/exports/');
