USE DATABASE INGEST_DB;

CREATE OR REPLACE STAGE OPS.STG_S3_EXPORTS
  URL = 's3://<YOUR_BUCKET_NAME>/<YOUR_PREFIX>/'
  STORAGE_INTEGRATION = s3_ingest_int
  FILE_FORMAT = OPS.FF_CSV_STD;

-- Optional: verify stage
LIST @OPS.STG_S3_EXPORTS;
