USE DATABASE INGEST_DB;

CREATE OR REPLACE TABLE CURATED.CUSTOMERS (
  CUSTOMER_ID  STRING,
  FULL_NAME    STRING,
  EMAIL        STRING,
  CITY         STRING,
  UPDATED_TS   TIMESTAMP_NTZ,
  SOURCE_FILE  STRING
);
