USE DATABASE INGEST_DB;

WITH latest_raw AS (
  SELECT
    CUSTOMER_ID,
    FULL_NAME,
    EMAIL,
    CITY,
    FILE_NAME,
    LOAD_TS
  FROM RAW.CUSTOMERS_RAW
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CUSTOMER_ID
    ORDER BY LOAD_TS DESC, ROW_NUMBER_IN_FILE DESC
  ) = 1
)

MERGE INTO CURATED.CUSTOMERS t
USING latest_raw s
  ON t.CUSTOMER_ID = s.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
  FULL_NAME   = s.FULL_NAME,
  EMAIL       = s.EMAIL,
  CITY        = s.CITY,
  UPDATED_TS  = CURRENT_TIMESTAMP(),
  SOURCE_FILE = s.FILE_NAME
WHEN NOT MATCHED THEN INSERT (
  CUSTOMER_ID, FULL_NAME, EMAIL, CITY, UPDATED_TS, SOURCE_FILE
) VALUES (
  s.CUSTOMER_ID, s.FULL_NAME, s.EMAIL, s.CITY, CURRENT_TIMESTAMP(), s.FILE_NAME
);

SELECT COUNT(*) AS curated_rows FROM CURATED.CUSTOMERS;
