USE DATABASE INGEST_DB;

CREATE OR REPLACE PIPE OPS.P_CUST_CSV_SNOWPIPE
  AUTO_INGEST = TRUE
AS
COPY INTO RAW.CUSTOMERS_RAW (
  FILE_NAME, ROW_NUMBER_IN_FILE,
  CUSTOMER_ID, FULL_NAME, EMAIL, CITY
)
FROM (
  SELECT
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER,
    $1::STRING,
    $2::STRING,
    $3::STRING,
    $4::STRING
  FROM @OPS.STG_S3_EXPORTS
)
FILE_FORMAT = (FORMAT_NAME = OPS.FF_CSV_STD)
ON_ERROR = 'CONTINUE';

-- Get notification channel details for AWS (you’ll use this in S3 event configuration)
DESC PIPE OPS.P_CUST_CSV_SNOWPIPE;
