USE DATABASE INGEST_DB;

-- See pipe status
SELECT SYSTEM$PIPE_STATUS('OPS.P_CUST_CSV_SNOWPIPE');

-- Copy history for the target table (last 1 day)
SELECT *
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'RAW.CUSTOMERS_RAW',
  START_TIME => DATEADD('day', -1, CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC;
