-- USE WAREHOUSE <YOUR_WAREHOUSE>;

CREATE OR REPLACE DATABASE INGEST_DB;
CREATE OR REPLACE SCHEMA INGEST_DB.RAW;
CREATE OR REPLACE SCHEMA INGEST_DB.CURATED;
CREATE OR REPLACE SCHEMA INGEST_DB.OPS;

USE DATABASE INGEST_DB;

-- Raw table for CSV example (customers)
CREATE OR REPLACE TABLE RAW.CUSTOMERS_RAW (
  LOAD_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FILE_NAME        STRING,
  ROW_NUMBER_IN_FILE NUMBER,
  CUSTOMER_ID      STRING,
  FULL_NAME        STRING,
  EMAIL            STRING,
  CITY             STRING
);

-- Raw table for JSON example (events)
CREATE OR REPLACE TABLE RAW.EVENTS_RAW (
  LOAD_TS    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FILE_NAME  STRING,
  PAYLOAD    VARIANT
);
