USE DATABASE INGEST_DB;

-- Load CSVs from S3 stage into RAW table
COPY INTO RAW.CUSTOMERS_RAW (
  FILE_NAME, ROW_NUMBER_IN_FILE,
  CUSTOMER_ID, FULL_NAME, EMAIL, CITY
)
FROM (
  SELECT
    METADATA$FILENAME        AS FILE_NAME,
    METADATA$FILE_ROW_NUMBER AS ROW_NUMBER_IN_FILE,
    $1::STRING               AS CUSTOMER_ID,
    $2::STRING               AS FULL_NAME,
    $3::STRING               AS EMAIL,
    $4::STRING               AS CITY
  FROM @OPS.STG_S3_EXPORTS
)
FILE_FORMAT = (FORMAT_NAME = OPS.FF_CSV_STD)
ON_ERROR = 'CONTINUE';

-- See per-file results for this COPY
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
