USE DATABASE INGEST_DB;

COPY INTO RAW.EVENTS_RAW (FILE_NAME, PAYLOAD)
FROM (
  SELECT
    METADATA$FILENAME AS FILE_NAME,
    PARSE_JSON($1)    AS PAYLOAD
  FROM @OPS.STG_S3_EXPORTS
)
FILE_FORMAT = (FORMAT_NAME = OPS.FF_JSON)
ON_ERROR = 'CONTINUE';

SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
